### ISSUE TITLE
TypeError: Cannot read property '1' of null     at IncomingMessage.<anonymous> (/root/.node-red/node_modules/smartfritz/lib/smartfritz.js:36:74)

### ISSUE THREAD

**Issue by ozett** [bashGroup/node-red-contrib-smartfritz#11]
it happed by accident....what to do now?

```
8 Jul 09:32:50 - [red] Uncaught Exception:
8 Jul 09:32:50 - TypeError: Cannot read property '1' of null
    at IncomingMessage.<anonymous> (/root/.node-red/node_modules/smartfritz/lib/smartfritz.js:36:74)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
root@deb8mpd-virt:~/.node-red#
```

**Comment by ozett** [comment]
no, wait..i changed the fritzbox-ip ....
but node-red does not start anymore...

where is the place to change it by hand?
